/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppBookmarksRouteImport } from './routes/_app/bookmarks'
import { Route as AppDownloadsRouteImport } from './routes/_app/downloads'
import { Route as AppHistoryRouteImport } from './routes/_app/history'
import { Route as AppLibraryRouteImport } from './routes/_app/library'
import { Route as AppStatisticsRouteImport } from './routes/_app/statistics'
import { Route as AppUpdatesRouteImport } from './routes/_app/updates'
import { Route as ReaderChapterIdRouteImport } from './routes/reader/$chapterId'
import { Route as AppBrowseExtensionsRouteImport } from './routes/_app/browse/extensions'
import { Route as AppBrowseGlobalSearchRouteImport } from './routes/_app/browse/global-search'
import { Route as AppMangaMangaIdRouteImport } from './routes/_app/manga/$mangaId'
import { Route as AppSettingsSectionRouteImport } from './routes/_app/settings/$section'
import { Route as AppBrowseSourcesIndexRouteImport } from './routes/_app/browse/sources.index'
import { Route as AppBrowseSourcesExtensionIdSourceKeyRouteImport } from './routes/_app/browse/sources.$extensionId.$sourceKey'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBookmarksRoute = AppBookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => AppRoute,
} as any)
const AppDownloadsRoute = AppDownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppStatisticsRoute = AppStatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => AppRoute,
} as any)
const AppUpdatesRoute = AppUpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => AppRoute,
} as any)
const ReaderChapterIdRoute = ReaderChapterIdRouteImport.update({
  id: '/reader/$chapterId',
  path: '/reader/$chapterId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBrowseExtensionsRoute = AppBrowseExtensionsRouteImport.update({
  id: '/browse/extensions',
  path: '/browse/extensions',
  getParentRoute: () => AppRoute,
} as any)
const AppBrowseGlobalSearchRoute = AppBrowseGlobalSearchRouteImport.update({
  id: '/browse/global-search',
  path: '/browse/global-search',
  getParentRoute: () => AppRoute,
} as any)
const AppMangaMangaIdRoute = AppMangaMangaIdRouteImport.update({
  id: '/manga/$mangaId',
  path: '/manga/$mangaId',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsSectionRoute = AppSettingsSectionRouteImport.update({
  id: '/settings/$section',
  path: '/settings/$section',
  getParentRoute: () => AppRoute,
} as any)
const AppBrowseSourcesIndexRoute = AppBrowseSourcesIndexRouteImport.update({
  id: '/browse/sources/',
  path: '/browse/sources/',
  getParentRoute: () => AppRoute,
} as any)
const AppBrowseSourcesExtensionIdSourceKeyRoute =
  AppBrowseSourcesExtensionIdSourceKeyRouteImport.update({
    id: '/browse/sources/$extensionId/$sourceKey',
    path: '/browse/sources/$extensionId/$sourceKey',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bookmarks': typeof AppBookmarksRoute
  '/downloads': typeof AppDownloadsRoute
  '/history': typeof AppHistoryRoute
  '/library': typeof AppLibraryRoute
  '/statistics': typeof AppStatisticsRoute
  '/updates': typeof AppUpdatesRoute
  '/reader/$chapterId': typeof ReaderChapterIdRoute
  '/browse/extensions': typeof AppBrowseExtensionsRoute
  '/browse/global-search': typeof AppBrowseGlobalSearchRoute
  '/manga/$mangaId': typeof AppMangaMangaIdRoute
  '/settings/$section': typeof AppSettingsSectionRoute
  '/browse/sources/': typeof AppBrowseSourcesIndexRoute
  '/browse/sources/$extensionId/$sourceKey': typeof AppBrowseSourcesExtensionIdSourceKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bookmarks': typeof AppBookmarksRoute
  '/downloads': typeof AppDownloadsRoute
  '/history': typeof AppHistoryRoute
  '/library': typeof AppLibraryRoute
  '/statistics': typeof AppStatisticsRoute
  '/updates': typeof AppUpdatesRoute
  '/reader/$chapterId': typeof ReaderChapterIdRoute
  '/browse/extensions': typeof AppBrowseExtensionsRoute
  '/browse/global-search': typeof AppBrowseGlobalSearchRoute
  '/manga/$mangaId': typeof AppMangaMangaIdRoute
  '/settings/$section': typeof AppSettingsSectionRoute
  '/browse/sources': typeof AppBrowseSourcesIndexRoute
  '/browse/sources/$extensionId/$sourceKey': typeof AppBrowseSourcesExtensionIdSourceKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/bookmarks': typeof AppBookmarksRoute
  '/_app/downloads': typeof AppDownloadsRoute
  '/_app/history': typeof AppHistoryRoute
  '/_app/library': typeof AppLibraryRoute
  '/_app/statistics': typeof AppStatisticsRoute
  '/_app/updates': typeof AppUpdatesRoute
  '/reader/$chapterId': typeof ReaderChapterIdRoute
  '/_app/browse/extensions': typeof AppBrowseExtensionsRoute
  '/_app/browse/global-search': typeof AppBrowseGlobalSearchRoute
  '/_app/manga/$mangaId': typeof AppMangaMangaIdRoute
  '/_app/settings/$section': typeof AppSettingsSectionRoute
  '/_app/browse/sources/': typeof AppBrowseSourcesIndexRoute
  '/_app/browse/sources/$extensionId/$sourceKey': typeof AppBrowseSourcesExtensionIdSourceKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bookmarks'
    | '/downloads'
    | '/history'
    | '/library'
    | '/statistics'
    | '/updates'
    | '/reader/$chapterId'
    | '/browse/extensions'
    | '/browse/global-search'
    | '/manga/$mangaId'
    | '/settings/$section'
    | '/browse/sources/'
    | '/browse/sources/$extensionId/$sourceKey'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bookmarks'
    | '/downloads'
    | '/history'
    | '/library'
    | '/statistics'
    | '/updates'
    | '/reader/$chapterId'
    | '/browse/extensions'
    | '/browse/global-search'
    | '/manga/$mangaId'
    | '/settings/$section'
    | '/browse/sources'
    | '/browse/sources/$extensionId/$sourceKey'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/bookmarks'
    | '/_app/downloads'
    | '/_app/history'
    | '/_app/library'
    | '/_app/statistics'
    | '/_app/updates'
    | '/reader/$chapterId'
    | '/_app/browse/extensions'
    | '/_app/browse/global-search'
    | '/_app/manga/$mangaId'
    | '/_app/settings/$section'
    | '/_app/browse/sources/'
    | '/_app/browse/sources/$extensionId/$sourceKey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ReaderChapterIdRoute: typeof ReaderChapterIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/bookmarks': {
      id: '/_app/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof AppBookmarksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/downloads': {
      id: '/_app/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof AppDownloadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/library': {
      id: '/_app/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/statistics': {
      id: '/_app/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof AppStatisticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/updates': {
      id: '/_app/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof AppUpdatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/reader/$chapterId': {
      id: '/reader/$chapterId'
      path: '/reader/$chapterId'
      fullPath: '/reader/$chapterId'
      preLoaderRoute: typeof ReaderChapterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/browse/extensions': {
      id: '/_app/browse/extensions'
      path: '/browse/extensions'
      fullPath: '/browse/extensions'
      preLoaderRoute: typeof AppBrowseExtensionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/browse/global-search': {
      id: '/_app/browse/global-search'
      path: '/browse/global-search'
      fullPath: '/browse/global-search'
      preLoaderRoute: typeof AppBrowseGlobalSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/manga/$mangaId': {
      id: '/_app/manga/$mangaId'
      path: '/manga/$mangaId'
      fullPath: '/manga/$mangaId'
      preLoaderRoute: typeof AppMangaMangaIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/$section': {
      id: '/_app/settings/$section'
      path: '/settings/$section'
      fullPath: '/settings/$section'
      preLoaderRoute: typeof AppSettingsSectionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/browse/sources/': {
      id: '/_app/browse/sources/'
      path: '/browse/sources'
      fullPath: '/browse/sources/'
      preLoaderRoute: typeof AppBrowseSourcesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/browse/sources/$extensionId/$sourceKey': {
      id: '/_app/browse/sources/$extensionId/$sourceKey'
      path: '/browse/sources/$extensionId/$sourceKey'
      fullPath: '/browse/sources/$extensionId/$sourceKey'
      preLoaderRoute: typeof AppBrowseSourcesExtensionIdSourceKeyRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBookmarksRoute: typeof AppBookmarksRoute
  AppDownloadsRoute: typeof AppDownloadsRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppLibraryRoute: typeof AppLibraryRoute
  AppStatisticsRoute: typeof AppStatisticsRoute
  AppUpdatesRoute: typeof AppUpdatesRoute
  AppBrowseExtensionsRoute: typeof AppBrowseExtensionsRoute
  AppBrowseGlobalSearchRoute: typeof AppBrowseGlobalSearchRoute
  AppMangaMangaIdRoute: typeof AppMangaMangaIdRoute
  AppSettingsSectionRoute: typeof AppSettingsSectionRoute
  AppBrowseSourcesIndexRoute: typeof AppBrowseSourcesIndexRoute
  AppBrowseSourcesExtensionIdSourceKeyRoute: typeof AppBrowseSourcesExtensionIdSourceKeyRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBookmarksRoute: AppBookmarksRoute,
  AppDownloadsRoute: AppDownloadsRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppLibraryRoute: AppLibraryRoute,
  AppStatisticsRoute: AppStatisticsRoute,
  AppUpdatesRoute: AppUpdatesRoute,
  AppBrowseExtensionsRoute: AppBrowseExtensionsRoute,
  AppBrowseGlobalSearchRoute: AppBrowseGlobalSearchRoute,
  AppMangaMangaIdRoute: AppMangaMangaIdRoute,
  AppSettingsSectionRoute: AppSettingsSectionRoute,
  AppBrowseSourcesIndexRoute: AppBrowseSourcesIndexRoute,
  AppBrowseSourcesExtensionIdSourceKeyRoute:
    AppBrowseSourcesExtensionIdSourceKeyRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ReaderChapterIdRoute: ReaderChapterIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
