// Channel names only (no zod), so the sandboxed preload can allowlist them cheaply.
export const INVOKE_CHANNELS = [
  'app.getInfo',
  'app.getLocale',
  'window.minimize',
  'window.toggleMaximize',
  'window.close',
  'window.isMaximized',
  'window.toggleFullScreen',
  'settings.get',
  'settings.set',
  'extensions.list',
  'extensions.loadDevFolder',
  'extensions.removeDevFolder',
  'extensions.reload',
  'extensions.preferences',
  'extensions.setPreference',
  'sources.list',
  'sources.info',
  'sources.filters',
  'sources.browse',
  'sources.resolveUrl',
  'sources.solveChallenge',
  'sources.setPinned',
  'manga.get',
  'manga.refresh',
  'manga.openInBrowser',
  'chapters.list',
  'chapter.get',
  'chapter.pages',
  'requests.cancel',
  'progress.save',
  'chapters.markRead',
  'chapters.markPreviousRead',
  'manga.continue',
  'reading.heartbeat',
  'reading.end',
  'history.list',
  'history.remove',
  'history.clear',
  'library.list',
  'library.counts',
  'library.add',
  'library.remove',
  'library.setCategories',
  'library.markRead',
  'categories.list',
  'categories.create',
  'categories.rename',
  'categories.delete',
  'categories.reorder',
  'manga.setCustomCover',
  'manga.resetCover',
  'manga.findDuplicates',
  'manga.setReaderSettings',
  'manga.setScanlatorPrefs',
  'manga.setChapterView',
  'migration.findCandidates',
  'migration.run',
  'downloads.enqueue',
  'downloads.list',
  'downloads.stats',
  'downloads.pause',
  'downloads.resume',
  'downloads.cancel',
  'downloads.retry',
  'downloads.reorder',
  'downloads.delete',
  'downloads.clearCompleted',
  'downloads.folder',
  'downloads.pickFolder',
  'downloads.setFolder',
  'downloads.openFolder',
  'chapters.setBookmarked',
] as const;
export type InvokeChannel = (typeof INVOKE_CHANNELS)[number];

export const EVENT_CHANNELS = [
  'window.maximizeChanged',
  'settings.changed',
  'db.changed',
  'cloudflare.status',
  'window.fullScreenChanged',
  'migration.progress',
  'downloads.progress',
  'downloads.moveProgress',
] as const;
export type EventChannel = (typeof EVENT_CHANNELS)[number];
